"""Phase 19.2: SDK code generator for Python, JavaScript, and R."""
from __future__ import annotations

from typing import Optional


def generate_python_sdk(base_url: str = "https://api.axiom.ftip.io", version: str = "v1") -> str:
    """Return a complete AXIOMClient Python class as a string (passes compile())."""
    return f'''"""AXIOM Python SDK — auto-generated by AXIOM Developer Platform."""
import json
import urllib.request
import urllib.error
from typing import Any, Dict, List, Optional


BASE_URL = "{base_url}"
VERSION = "{version}"


class AXIOMError(Exception):
    def __init__(self, status_code: int, message: str) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.message = message


class AXIOMClient:
    def __init__(self, api_key: str, base_url: str = BASE_URL) -> None:
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self._headers = {{
            "X-API-Key": api_key,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }}

    def _request(self, method: str, path: str, body: Optional[Dict] = None) -> Any:
        url = self.base_url + path
        data = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=data, headers=self._headers, method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as exc:
            msg = exc.read().decode() if hasattr(exc, "read") else str(exc)
            raise AXIOMError(exc.code, msg) from exc

    def get_signal(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/prosperity/signal/{{symbol.upper()}}")

    def get_snapshot(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/prosperity/snapshot/{{symbol.upper()}}")

    def get_universe(self) -> List[str]:
        result = self._request("GET", "/prosperity/universe")
        return result.get("symbols", [])

    def batch_signals(self, symbols: List[str]) -> Dict[str, Any]:
        return self._request("POST", "/prosperity/batch", {{"symbols": symbols}})

    def get_axiom_scores(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/axiom/scores/{{symbol.upper()}}")

    def get_axiom_history(self, symbol: str, lookback_days: int = 63) -> List[Dict[str, Any]]:
        return self._request("GET", f"/axiom/history/{{symbol.upper()}}?lookback_days={{lookback_days}}")

    def get_sri(self) -> Dict[str, Any]:
        return self._request("GET", "/axiom/risk/sri")

    def get_sri_history(self, lookback_days: int = 63) -> List[Dict[str, Any]]:
        return self._request("GET", f"/axiom/risk/sri/history?lookback_days={{lookback_days}}")

    def get_universal_intelligence(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/intelligence/universal/{{symbol.upper()}}")

    def get_competitive_report(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/competitive/{{symbol.upper()}}")

    def get_head_to_head(self, symbol: str, competitor: str) -> Dict[str, Any]:
        return self._request("GET", f"/competitive/{{symbol.upper()}}/vs/{{competitor.upper()}}")

    def get_management_quality(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/competitive/{{symbol.upper()}}/management-quality")

    def get_macro_regime(self) -> Dict[str, Any]:
        return self._request("GET", "/macro/regime")

    def get_cross_asset_snapshot(self) -> Dict[str, Any]:
        return self._request("GET", "/macro/cross-asset")

    def explain_signal(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/explain/{{symbol.upper()}}")

    def get_research_report(self, symbol: str) -> Dict[str, Any]:
        return self._request("GET", f"/explain/report/{{symbol.upper()}}")

    def get_morning_briefing(self, as_of_date: Optional[str] = None) -> Dict[str, Any]:
        path = "/jobs/briefing/morning"
        if as_of_date:
            path += f"?as_of_date={{as_of_date}}"
        return self._request("GET", path)

    def get_system_health(self) -> Dict[str, Any]:
        return self._request("GET", "/orchestration/health")

    def subscribe_webhook(self, event_type: str, callback_url: str,
                          secret: str, filter_config: Optional[Dict] = None) -> Dict[str, Any]:
        return self._request("POST", "/developer/webhooks", {{
            "event_type": event_type,
            "callback_url": callback_url,
            "secret": secret,
            "filter": filter_config or {{}},
        }})

    def get_usage_metrics(self, period: str = "7d") -> Dict[str, Any]:
        return self._request("GET", f"/developer/usage?period={{period}}")

    def get_api_docs(self) -> Dict[str, Any]:
        return self._request("GET", "/developer/api-docs")
'''


def generate_javascript_sdk(base_url: str = "https://api.axiom.ftip.io") -> str:
    """Return a complete AXIOMClient ES6 async class as a string."""
    return f"""/**
 * AXIOM JavaScript SDK — auto-generated by AXIOM Developer Platform.
 * @version 1.0.0
 */

const BASE_URL = '{base_url}';

class AXIOMError extends Error {{
  constructor(statusCode, message) {{
    super(message);
    this.name = 'AXIOMError';
    this.statusCode = statusCode;
  }}
}}

class AXIOMClient {{
  constructor(apiKey, baseUrl = BASE_URL) {{
    this.apiKey = apiKey;
    this.baseUrl = baseUrl.replace(/\\/$/, '');
    this._headers = {{
      'X-API-Key': apiKey,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    }};
  }}

  async _request(method, path, body = null) {{
    const url = this.baseUrl + path;
    const options = {{ method, headers: this._headers }};
    if (body !== null) options.body = JSON.stringify(body);
    const res = await fetch(url, options);
    const data = await res.json();
    if (!res.ok) throw new AXIOMError(res.status, data.detail || res.statusText);
    return data;
  }}

  getSignal(symbol) {{
    return this._request('GET', `/prosperity/signal/${{symbol.toUpperCase()}}`);
  }}

  getSnapshot(symbol) {{
    return this._request('GET', `/prosperity/snapshot/${{symbol.toUpperCase()}}`);
  }}

  getUniverse() {{
    return this._request('GET', '/prosperity/universe');
  }}

  batchSignals(symbols) {{
    return this._request('POST', '/prosperity/batch', {{ symbols }});
  }}

  getAxiomScores(symbol) {{
    return this._request('GET', `/axiom/scores/${{symbol.toUpperCase()}}`);
  }}

  getSRI() {{
    return this._request('GET', '/axiom/risk/sri');
  }}

  getUniversalIntelligence(symbol) {{
    return this._request('GET', `/intelligence/universal/${{symbol.toUpperCase()}}`);
  }}

  getCompetitiveReport(symbol) {{
    return this._request('GET', `/competitive/${{symbol.toUpperCase()}}`);
  }}

  getHeadToHead(symbol, competitor) {{
    return this._request('GET', `/competitive/${{symbol.toUpperCase()}}/vs/${{competitor.toUpperCase()}}`);
  }}

  getMacroRegime() {{
    return this._request('GET', '/macro/regime');
  }}

  explainSignal(symbol) {{
    return this._request('GET', `/explain/${{symbol.toUpperCase()}}`);
  }}

  getMorningBriefing(asOfDate = null) {{
    const path = asOfDate
      ? `/jobs/briefing/morning?as_of_date=${{asOfDate}}`
      : '/jobs/briefing/morning';
    return this._request('GET', path);
  }}

  getSystemHealth() {{
    return this._request('GET', '/orchestration/health');
  }}

  subscribeWebhook(eventType, callbackUrl, secret, filterConfig = {{}}) {{
    return this._request('POST', '/developer/webhooks', {{
      event_type: eventType,
      callback_url: callbackUrl,
      secret,
      filter: filterConfig,
    }});
  }}

  getUsageMetrics(period = '7d') {{
    return this._request('GET', `/developer/usage?period=${{period}}`);
  }}

  getApiDocs() {{
    return this._request('GET', '/developer/api-docs');
  }}
}}

if (typeof module !== 'undefined') {{
  module.exports = {{ AXIOMClient, AXIOMError }};
}}
"""


def generate_r_sdk(base_url: str = "https://api.axiom.ftip.io") -> str:
    """Return an R SDK stub as a string."""
    return f"""# AXIOM R SDK — auto-generated by AXIOM Developer Platform.
# Requires: httr, jsonlite

library(httr)
library(jsonlite)

BASE_URL <- "{base_url}"

axiom_client <- function(api_key, base_url = BASE_URL) {{
  list(api_key = api_key, base_url = base_url)
}}

.axiom_request <- function(client, method, path, body = NULL) {{
  url <- paste0(client$base_url, path)
  headers <- add_headers("X-API-Key" = client$api_key, "Accept" = "application/json")
  if (!is.null(body)) {{
    res <- VERB(method, url, headers, body = toJSON(body, auto_unbox = TRUE),
                encode = "json")
  }} else {{
    res <- VERB(method, url, headers)
  }}
  if (http_error(res)) stop(paste("AXIOM API error:", status_code(res)))
  fromJSON(content(res, "text", encoding = "UTF-8"), simplifyVector = FALSE)
}}

axiom_get_signal <- function(client, symbol) {{
  .axiom_request(client, "GET", paste0("/prosperity/signal/", toupper(symbol)))
}}

axiom_get_snapshot <- function(client, symbol) {{
  .axiom_request(client, "GET", paste0("/prosperity/snapshot/", toupper(symbol)))
}}

axiom_get_sri <- function(client) {{
  .axiom_request(client, "GET", "/axiom/risk/sri")
}}

axiom_get_macro_regime <- function(client) {{
  .axiom_request(client, "GET", "/macro/regime")
}}

axiom_get_morning_briefing <- function(client, as_of_date = NULL) {{
  path <- "/jobs/briefing/morning"
  if (!is.null(as_of_date)) path <- paste0(path, "?as_of_date=", as_of_date)
  .axiom_request(client, "GET", path)
}}
"""
